### PR TITLE
Automating DR-7 and fixing rogue bugs

### LINKED ISSUE #71: Automate DR-7
If a container registry is provided, we should be able to check for geo-replication

### PR DESCRIPTION
**Pull request by brian-workman**
Closes #71

### CODE REVIEW

File: modules/disasterRecovery.js [hunk 1]
```diff
@@ -119,4 +120,79 @@ export function checkForControlPlaneSla(clusterDetails) {
...
+
+    // For premium registries we need to query replications
+    try {
+      var commandResults = await executeCommand(`az acr replication list -r ${registry.name}`);
+      var registryReplications = JSON.parse(commandResults.stdout);
+      if (registryReplications.length <= 1)
+        registriesWithoutReplication.push(registry.name);
+    }
+    catch (e) {
+      console.log(chalk.red(`--- An error occurred retrieving ACR replications: ${e}`));
```
Comment (fgauna12) [inline modules/disasterRecovery.js:167]: Could we just return with an error and not use `console.log`?

**Review by fgauna12 — CHANGES_REQUESTED** [review]

File: modules/disasterRecovery.js (hunk 1 above)
Comment (brian-workman) [reply modules/disasterRecovery.js]: Done.

**Review by fgauna12 — APPROVED** [review]
Looks good!
